spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: virtualtest
    username: admin
    password: admin
    listener:
      simple:
        concurrency: 10  # 定义消费者数量
        max-concurrency: 10
        prefetch: 1 # 每次从队列中取多少条数据
        auto-startup: true #
        default-requeue-rejected: true

server:
  port: 8080



